"""
core/state_map.py — StateMap data model & serialisation.

Defines the data structures that represent a protocol's entire state space:
contracts, state variables, function flows, and economic invariants.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    QA = "QA"
    GAS = "Gas"


class Visibility(str, Enum):
    PUBLIC = "public"
    EXTERNAL = "external"
    INTERNAL = "internal"
    PRIVATE = "private"


class Mutability(str, Enum):
    PURE = "pure"
    VIEW = "view"
    NONPAYABLE = "nonpayable"
    PAYABLE = "payable"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class StateVariable:
    """A single state variable in a contract."""
    name: str
    var_type: str
    visibility: str = "internal"
    is_mapping: bool = False
    is_array: bool = False
    slot: Optional[int] = None

    def __hash__(self):
        return hash(self.name)


@dataclass
class FunctionFlow:
    """Represents a function and its call/state relationships."""
    name: str
    contract: str
    visibility: str = "public"
    mutability: str = "nonpayable"
    modifiers: list[str] = field(default_factory=list)
    reads: list[str] = field(default_factory=list)       # state vars read
    writes: list[str] = field(default_factory=list)      # state vars written
    internal_calls: list[str] = field(default_factory=list)
    external_calls: list[str] = field(default_factory=list)
    parameters: list[dict] = field(default_factory=list)  # [{name, type}]
    returns: list[dict] = field(default_factory=list)

    @property
    def signature(self) -> str:
        params = ", ".join(p.get("type", "unknown") for p in self.parameters)
        return f"{self.name}({params})"


@dataclass
class EconomicInvariant:
    """
    An economic property that must hold true at all times.
    
    Examples:
      - "Total assets should equal sum of user balances"
      - "Share price should never decrease outside of a loss event"
    """
    id: str
    description: str
    expression: str                     # Solidity-like assertion expression
    severity_if_violated: str = "High"
    related_variables: list[str] = field(default_factory=list)
    related_functions: list[str] = field(default_factory=list)
    category: str = "general"           # cross_chain, economic, agent_payment
    auto_generated: bool = False


@dataclass
class Anomaly:
    """A deviation from expected patterns detected during analysis."""
    id: str
    description: str
    location: str                       # contract::function or file:line
    anomaly_type: str                   # "custom_implementation", "missing_check", etc.
    severity_hint: str = "Medium"
    related_invariants: list[str] = field(default_factory=list)
    details: dict = field(default_factory=dict)


@dataclass
class ExploitHypothesis:
    """A chain-exploit hypothesis generated by the reasoner."""
    id: str
    description: str
    chain: list[str]                    # ordered list of function calls
    violated_invariant: str             # invariant ID
    economic_impact: str
    confidence: float = 0.0            # 0.0–1.0
    anomalies_used: list[str] = field(default_factory=list)


@dataclass
class FuzzResult:
    """Result from running a Foundry invariant test."""
    hypothesis_id: str
    passed: bool
    counterexample: Optional[str] = None
    trace: Optional[str] = None
    gas_used: Optional[int] = None
    forge_output: str = ""


@dataclass
class Finding:
    """A confirmed security finding ready for reporting."""
    id: str
    title: str
    severity: str
    description: str
    impact: str
    proof_of_concept: str              # Solidity test code or file path
    recommendation: str
    contract: str
    function: str
    category: str = "general"
    forge_output: str = ""
    hypothesis: Optional[ExploitHypothesis] = None


@dataclass
class Contract:
    """Represents a single Solidity contract."""
    name: str
    file_path: str
    is_interface: bool = False
    is_abstract: bool = False
    is_library: bool = False
    inherits: list[str] = field(default_factory=list)
    state_variables: list[StateVariable] = field(default_factory=list)
    functions: list[FunctionFlow] = field(default_factory=list)
    modifiers: list[str] = field(default_factory=list)
    events: list[str] = field(default_factory=list)


@dataclass
class StateMap:
    """
    The complete state-space representation of a protocol.
    
    This is the central data structure that flows through the entire
    Bloodhound pipeline: mapper → reasoner → fuzzer → reporter.
    """
    protocol_name: str
    repo_path: str
    contracts: list[Contract] = field(default_factory=list)
    invariants: list[EconomicInvariant] = field(default_factory=list)
    anomalies: list[Anomaly] = field(default_factory=list)
    hypotheses: list[ExploitHypothesis] = field(default_factory=list)
    findings: list[Finding] = field(default_factory=list)

    # ---- Serialisation ----

    def to_dict(self) -> dict:
        """Convert the entire state map to a JSON-serializable dict."""
        return asdict(self)

    def to_json(self, path: str | Path | None = None, indent: int = 2) -> str:
        """Serialize to JSON string and optionally write to file."""
        data = json.dumps(self.to_dict(), indent=indent, default=str)
        if path:
            p = Path(path)
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(data, encoding="utf-8")
        return data

    @classmethod
    def from_json(cls, path: str | Path) -> "StateMap":
        """Deserialize a StateMap from a JSON file."""
        raw = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls._from_dict(raw)

    @classmethod
    def _from_dict(cls, d: dict) -> "StateMap":
        """Recursively reconstruct dataclass instances from a dict."""
        contracts = [
            Contract(
                **{
                    **c,
                    "state_variables": [StateVariable(**sv) for sv in c.get("state_variables", [])],
                    "functions": [FunctionFlow(**f) for f in c.get("functions", [])],
                }
            )
            for c in d.get("contracts", [])
        ]
        invariants = [EconomicInvariant(**inv) for inv in d.get("invariants", [])]
        anomalies = [Anomaly(**a) for a in d.get("anomalies", [])]
        hypotheses = [ExploitHypothesis(**h) for h in d.get("hypotheses", [])]
        findings = [
            Finding(**{**f, "hypothesis": ExploitHypothesis(**f["hypothesis"]) if f.get("hypothesis") else None})
            for f in d.get("findings", [])
        ]
        return cls(
            protocol_name=d.get("protocol_name", "unknown"),
            repo_path=d.get("repo_path", ""),
            contracts=contracts,
            invariants=invariants,
            anomalies=anomalies,
            hypotheses=hypotheses,
            findings=findings,
        )

    # ---- Queries ----

    def get_contract(self, name: str) -> Contract | None:
        """Find a contract by name."""
        return next((c for c in self.contracts if c.name == name), None)

    def get_invariant(self, inv_id: str) -> EconomicInvariant | None:
        """Find an invariant by ID."""
        return next((i for i in self.invariants if i.id == inv_id), None)

    def get_all_functions(self) -> list[FunctionFlow]:
        """Return a flat list of all functions across all contracts."""
        return [f for c in self.contracts for f in c.functions]

    def get_external_entrypoints(self) -> list[FunctionFlow]:
        """Return all public/external non-view functions (potential attack surface)."""
        return [
            f for f in self.get_all_functions()
            if f.visibility in ("public", "external")
            and f.mutability not in ("pure", "view")
        ]

    def generate_mermaid_diagram(self) -> str:
        """Generate a Mermaid flowchart of the protocol relationships."""
        lines = ["graph TD"]
        
        # Add contract nodes
        for c in self.contracts:
            if c.is_interface:
                lines.append(f'    {c.name}["{c.name}\\n(interface)"]:::interface')
            elif c.is_library:
                lines.append(f'    {c.name}["{c.name}\\n(library)"]:::library')
            else:
                lines.append(f'    {c.name}["{c.name}"]:::contract')

        # Add inheritance edges
        for c in self.contracts:
            for parent in c.inherits:
                lines.append(f"    {parent} -->|inherits| {c.name}")

        # Add cross-contract call edges
        for c in self.contracts:
            for fn in c.functions:
                for ext in fn.external_calls:
                    # Parse "ContractName.functionName" format
                    parts = ext.split(".")
                    if len(parts) == 2:
                        target_contract = parts[0]
                        lines.append(
                            f"    {c.name} -->|{fn.name} → {parts[1]}| {target_contract}"
                        )

        # Style classes
        lines.append("")
        lines.append("    classDef contract fill:#1a1a2e,stroke:#e94560,color:#fff")
        lines.append("    classDef interface fill:#16213e,stroke:#0f3460,color:#aaa,stroke-dasharray: 5 5")
        lines.append("    classDef library fill:#0f3460,stroke:#533483,color:#aaa")

        return "\n".join(lines)
